### ISSUE TITLE
Include CancellationToken in queries

### ISSUE THREAD

**Issue by Kpaubert** [IT2901-SINTEF01/backend#101]
### Description
Including a CancellationToken will stop the application from throwing error if someone cancels a request before it is finished.

### Subtasks
- [ ] Add working CancellationTokens to queries that are vulnerable to this issue.

**Comment by FredrikAugust** [comment]
cancel culture has gone too far......

**Comment by FredrikAugust** [comment]
Closing for now. Reopen if necessary.
