### ISSUE TITLE
Select datasource for MVP

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/backend#15]
### Question

We need to select a datasource for use in the MVP. We should choose one that is preferably quite small, has a simple type, and has no rate limiting.

**Comment by fredrikbw** [comment]
[api.met](https://api.met.no/weatherapi/airqualityforecast/0.1/documentation)

**Comment by FredrikAugust** [comment]
Could you provide some explanation and more information, @fredrikbw.

**Comment by fredrikbw** [comment]
Of course @FredrikAugust !

### Alternative 1:
Found a better API than the one mentioned above(same provider, different endpoint)
**Location forecast from Meteorologisk Institutt.** 
https://api.met.no/weatherapi/locationforecast/2.0/
This service delivers a full weather forecast for one location, that is, a forecast with several parameters for a nine-day period.


Has both a _/complete_ and a _/compact endpoint_. I think we should use the _/compact_ for now, as it doesn't contain too much data, only the most used parameters.

The parameters for a request are **lat** and **long**, both are of Data Type float and are required. One can also specify altitude (integer).

Terms of Service is available [here](https://api.met.no/doc/TermsOfService)

**PROS**:
* Well documentet
* Relevant for this projects as it has geographical features.

**CONS**:
* The compact version might still be too large.

**Limitation of usage:** 
* Anything over 20 requests/second per application (total, not per client) requires special agreement.
* 
> All requests must (if possible) include an identifying User Agent-string (UA) in the request with the application/domain name, optionally version number. You should also include a company email address or a link to the company website where we can find contact information. If we cannot contact you in case of problems, you risk being blocked without warning.

* Cross-origin requests has to use an _Origin_

### Alternative 2:
Use an API from SSB
https://data.ssb.no/api/v0/dataset/

**Comment by FredrikAugust** [comment]
Great work, @fredrikbw! 

I will leave it to you to decide which one we will use for the MVP!

Once you have decided, leave a comment here saying "Decision made: Alternative 1" or something along those lines and close the issue:)

**Comment by fredrikbw** [comment]
Decision : alternative 1
