### ISSUE TITLE
Testing of data delivery and graphql

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/backend#20]
### Description
The application should be thoroughly tested to ensure no bugs make it out into production.
I will leave it up to @Kpaubert to decide what parts of the applications should be tested in this issue, and how.

### Subtasks
- [x] Create test folder- and file structure

Ideas for things to test, feel free to replace/add:
- [x] Test data retrieval (perhaps with mocking)

**Comment by Kpaubert** [comment]
@FredrikAugust Perhaps hold back a bit on the query resolution so we can close this a bit faster, and use that for the next milestone? I would argue the testing for a functional prototype does not require it. Thoughts?

**Comment by FredrikAugust** [comment]
I'm a bit torn, but I do agree that "moving fast" might be a better approach here.

What we're testing here is essentially just if the MetAPI works as we expect – which is only helpful if it somehow stops working.

On the other hand; most of the other functionality is handled by the GraphQL library – returning the correct data from the POCO to the GraphQL "caller" (client). 

I think we can omit the part you discussed here, and create a new issue for it which tests some of the more complex field resolvers – and makes sure that they return the expected content. For this however, we should mock the response of the API to prevent sending a lot of requests.

I think we should generally try to avoid side effects in unit tests (incl. sending requests to third-party APIs). If possible, it would be nice if you could disable the tests that call an API by default, and then we can run them manually _every once in a while_ (perhaps also in CI once we release a new _release_).

**Comment by Kpaubert** [comment]
Sounds good!

The mocking branch is quite far behind with regards to commits, and as the testing branch (20-data-delivery-test) has some of the logic I would want for setting up mocking, I think I'll scrap the other one (16-initial-mocking-service). I'll look into mocking libraries, choose one that fits , our use (perhaps [bogus as you references here](https://github.com/IT2901-SINTEF01/backend/pull/23#issuecomment-779853638)).

I removed one of the checks on #16. So my plan is now:
1. Merge master into the testing branch (20) so it's not too far behind
2. Implement mocking
3. Verify that it works using the tests that already exists, just with mocked data
4. Implement/plan for how to use the mocking functionality in the actual backend

**Comment by FredrikAugust** [comment]
That sounds like a smart plan! :rocket:
