### ISSUE TITLE
Investigate cloud services

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/backend#46]
### Question

Should we deploy our solution to a cloud service to make it easier to use for the frontend team? It would also make the project more accessible to end-users.

### Related information

- Azure
- AWS
- GCP
- Github Actions (Action to push to e.g. Azure)

**Comment by FredrikAugust** [comment]
If you decide to do this, I would recommend deploying one staging build and one production build. We can start with only deploying a staging build to avoid excessive use of the APIs.

**Comment by FredrikAugust** [comment]
When you're done discussing and deciding, notify me of the decision and I'll set up a work package:)

**Comment by fredrikbw** [comment]
Seems very possible to deploy the [umbrella repo](https://github.com/IT2901-SINTEF01/umbrella) on Azure. There is support for multi-container application, and it's possible to enable Continuous Deployment in the Azure interface.

Reasoning is based on the following:
* https://docs.docker.com/cloud/aci-integration/
* https://www.youtube.com/watch?v=O5aXcmKc1HU&ab_channel=TravisMedia

**Comment by FredrikAugust** [comment]
Wonderful!

I set up a work package for this (#65).

**Comment by FredrikAugust** [comment]
To propose a simple solution;

- Auto-deploy backend (alone) to Azure
- Host frontend on github pages (static site only)

**Comment by FredrikAugust** [comment]
@IT2901-SINTEF01/backend 

Does this sound sound? If so, I'll close the issue.

Should also make #65 a lot easier.

**Comment by FredrikAugust** [comment]
Note to self: this requires extra issue on frontend for deployment there.

**Comment by FredrikAugust** [comment]
Decision.

Azure.
