### ISSUE TITLE
Create generic GraphQL type which includes metadata

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/backend#63]
### Description
Instead of adding metadata as a field to all queries, we could use a generic type which "injects" this.

### Subtasks
- [ ] Create generic type
- [ ] Test type

**Comment by fredrikbw** [comment]
Could you elaborate a bit more on what you envision for this? Like should the generic type inject metadata into the query for each data source?

**Comment by FredrikAugust** [comment]
Yes!

You could create a class which is named `DataSourceWithMetadata` which in it's constructor has 

```c#
public DataSourceWithMetadata(string name)
{
    Field(metadata setup, resolver: () => GetByName(name));
}
```

And then inherit from it in the other graphql types. Thus you would have to include the metadata manually, and only specify the metadata field name (so it can retrieve from DB).

E.g.

```c#
class CatsWithHatsType : DataSourceWithMetadata
{
    public CatsWithHatsType() : base("cats_with_hats")
    {
        // get the cats!!! 🐈 
    }
}
```
