### ISSUE TITLE
Investigate Continuous Deployment with Azure and docker-compose 🐳🔍 

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/backend#65]
### Description

Take a look at how we can achieve Continuous Deployment to Azure using Github Actions (our CI pipeline).

You can deploy from the umbrella repo as that contains the `docker-compose.yml` file.

You might have to add some custom configuration to `backend` and `frontend` to make the deployment react to changes in those repositories.

### Subtasks
- [x] Deploy `docker-compose` to Azure
- [x] Make it update when you push to either front- or backend repo

**Comment by FredrikAugust** [comment]
Since Azure has very simple deployment of ASP.Net applications we could consider deploying our application straight to it, without any docker setup.

What do you think of this approach, @IT2901-SINTEF01/backend?

**Comment by Kpaubert** [comment]
If that seems like the best way to do it, I'm A-okay with it 😄 

Just a couple of questions. Does this mean we will not use `docker-compose` to set up the entire project using the umbrella repository? How will our MongoDB server be deployed?

**Comment by FredrikAugust** [comment]
I’m thinking we can deploy a manually configured Azure-backed infrastructure ourselves, but provide the option for deploying using Umbrella-repository for end-users.

For azure, MongoDB can be handled with Atlas or other DBaaS, and for umbrella it will be added to the docker-compose configuration.

xoxo
Fredrik

**Comment by FredrikAugust** [comment]
No docker compose
