### ISSUE TITLE
Codacy and Rider Code Cleanup work against each other

### ISSUE THREAD

**Issue by fredrikbw** [IT2901-SINTEF01/backend#71]
### Description
The Codacy Static Code Analysis will mark lacking curly-braces in for loops as bad, Code Cleanup will remove them.

### Steps to reproduce
1. Create for loop that has curly braces, example:
```
for (var i = 0; i < 10; i++) {DoSomething();}
```
2. Perform Rider Code Cleanup, for loop will be;
```
for (var i = 0; i < 10; i++) DoSomething();
```
3. Codacy check will fail.

**Comment by FredrikAugust** [comment]
@blauks

**Comment by FredrikAugust** [comment]
For the record, it's also possible to configure rider to format this in Codacy's preferred format.

**Comment by blauks** [comment]
I will take a look

**Comment by blauks** [comment]
This shouldn't be an issue now

**Comment by FredrikAugust** [comment]
Issue? 🙅🏻

**Comment by blauks** [comment]
😃
