### ISSUE TITLE
OptionsMiddleware should inherit from IMiddleware

### ISSUE THREAD

**Issue by Kpaubert** [IT2901-SINTEF01/backend#79]
IMO, OptionsMiddleware should inherit from IMiddleware, given that it uses the funcionality implemented in the interface.

### Question
- [x] Discuss

### Related information
https://github.com/IT2901-SINTEF01/backend/blob/master/utils/OptionsMiddleware.cs#L12

**Comment by FredrikAugust** [comment]
Great idea, can you fix this?

**Comment by Kpaubert** [comment]
Yes indeed. Will be fixed posthaste.

**Comment by Kpaubert** [comment]
Closed by #80
