### ISSUE TITLE
SSB Population Data is hard to understand/work with

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/backend#94]
### Description
Right now, the SSB population data _data source_ is quite hard to understand and work with, and thus I believe (emphasis: _I_. Thus the `question` label – please share your thoughts) it might be helpful to do some cleanup of the data before sending it over to frontend.

If I'm not mistaken, the data is on GeoJSON format, which means we might be able to abstract this cleanup and reuse it later.

#### Proposed actions
- Provide a refined query which allows you to request the population for several municipalities using e.g. an array of enum values; `[Municipality.Oslo, Municipality.Trondheim]` or something along those lines. This requires the creation of an enum with all the municipalities, but I believe this should be doable with some minimal scripting in python. Rumor has it @Kpaubert is a God at this
- Clean up the data so that the returned data to frontend is similar to `{ municipalities: [...], populations: [...] }`. This would make it a lot easier to chart

### Subtasks
- [x] Decide what to do. Paging @IT2901-SINTEF01/frontend for discussion; how would you like the data to look? 
- [x] Implement eventual changes
- [x] Test!

**Comment by Kpaubert** [comment]
I like the idea, as it's likely that the user doesn't need all data at once. With the json-stat format, modifying the data to do what is asked in the question seems very doable after the data is fetched. The data is however <b>not</b> on the GeoJSON format, but being json-stat, it can still be very much reusable.

I'm guessing it's possible to pass parameters to GraphQL in a manner that would look like:
```graphql
query {
   populationsInNorway(['Bodo', Trondheim]) {
      ...
   }
}
```
In which case, creating a helper class/method within the class to put together the correct dataset should be a walk in park<sub>don't quote me on that</sub>.

<details>
<summary>Example JSON (just for structure, with emphasis on the parts important for implementing the functionality described in the question)</summary>

<pre><code>
{
  "data": {
    "populationsInNorway": {
      "metadata": {
        "name": "Befolkning. Kommuner, pr. 1.1., 1986 - siste år"
      },
      "dataset": {
        "source": "Statistisk sentralbyrå",
        "updated": "2021-02-28T00:00:00.0007427+01:00",
        "label": "07459: Befolkning, etter region, år og statistikkvariabel",
        "dimension": {
          "id": [...],
          "region": {
            "category": {
              "index": {
                "keys": [
                  "K-3001",
                  "K-3002",
                  "K-3003",
                  ...
                ],
                "values": [
                  0,
                  1,
                  2,
                  ...
                ]
              },
              "label": {
                "keys": [
                  "K-3001",
                  "K-3002",
                  "K-3003",
                  ...
                ],
                "values": [
                  "Halden",
                  "Moss",
                  "Sarpsborg",
                  ...
                ]
              }
            },
            "label": "Label"
          },
          "role": {...},
<hr>
          <b>"size": [
            359,
            36
          ],</b>
<hr>
          "tid": {
            "category": {
              "index": {
                "keys": [
                  "1986",
                  "1987",
                  "1988",
                  ...
                ],
                "values": [
                  0,
                  1,
                  2,
                  ...
                ]
              },
              "label": {
                "keys": [
                  "1986",
                  "1987",
                  "1988",
                  ...
                ],
                "values": [
                  "1986",
                  "1987",
                  "1988",
                  ...
                ]
              }
            },
            "label": "År"
          }
        },
<hr>
        <b>"value": [
          7820,
          15338,
          12638,
          ...
        ]</b>
<hr>
      }
    }
  }
}
</code></pre>

</details>

Regarding the enums: should we store all the municipalities/municipality indices in the frontend (in assets or whatever), or should they be fetched from the backend?

**Comment by FredrikAugust** [comment]
Change made:
<img width="1283" alt="Screenshot 2021-03-24 at 10 39 29" src="https://user-images.githubusercontent.com/7691547/112287999-373db380-8c8d-11eb-8894-4199362a3d9f.png">
You can now request all the available municipalities (which you can use when querying this query later).
